#!/usr/bin/env python3

import requests

def download_file_from_google_drive(id, destination):
    """
    Download requested file through http requests

    @param id: File ID from gdrive sharable link
    @param destination: target file location
    """

    def get_confirm_token(response):
        for key, value in response.cookies.items():
            if key.startswith('download_warning'):
                return value

        return None

    def save_response_content(response, destination):
        CHUNK_SIZE = 32768

        with open(destination, "wb") as f:
            for chunk in response.iter_content(CHUNK_SIZE):
                if chunk: # filter out keep-alive new chunks
                    f.write(chunk)

    URL = "https://docs.google.com/uc?export=download"

    session = requests.Session()

    response = session.get(URL, params = { 'id' : id }, stream = True)
    token = get_confirm_token(response)

    if token:
        params = { 'id' : id, 'confirm' : token }
        response = session.get(URL, params = params, stream = True)

    save_response_content(response, destination)    


if __name__ == "__main__":
    FILE_ID="1gwywIVIGBq8oQDgYBrJQ0CSW_-Q4R7Oq"
    TARGET="rover_descriptions/meshes.tar.gz"
    print(f'Downloading meshes from file {FILE_ID} to {TARGET}')

    download_file_from_google_drive(FILE_ID, TARGET)
    print('Download Complete')

    import tarfile
    file = tarfile.open(TARGET)
    file.extractall('rover_descriptions/meshes')
    file.close()
    print('Extraction Complete')

    import os
    os.remove(TARGET) 
    print('Cleaned Mesh Directory')

